### ISSUE TITLE
Clear item from history

### ISSUE THREAD

**Issue by kabradshaw1** [bslockhart/The-Inspired-Recipe#13]
*Description*

- Could at a button or icon next to each searched item and functions to specifically remove that item.

**Comment by jrargent** [comment]
Good idea. Seems better from the user side to be able to clear specific items as well as being able to clear everything. 

I think this alongside the clear all would be more beneficial to users.

**Comment by jrargent** [comment]
I have a suggestion for this. Since part of the grading requirement mentions using modals, could we add a modal that pops up after hitting delete, saying something like "are you sure you wish to delete the selected item?"
